# Generated by Django 5.0.4 on 2024-05-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=50)),
                ('scientific_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images')),
                ('season', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=3)),
            ],
        ),
    ]
